version: '2'
services:

  server:
    extends:
      file: docker-compose.yml
      service: server

  # mysql:
  #   extends:
  #     file: docker-compose.yml
  #     service: mysql

  test:
    image: jguillermo/api-test:latest
    volumes:
      - ./app/e2e:/app/e2e
    depends_on:
       - server
      #  - mysql
    command: "/tmp/wait-for-it.sh server:8056 -t 5 -- npm test"



