version: '2'
services:

  server:
    extends:
      file: docker-compose.yml
      service: server
    networks:
      - api-test-network

  server-fake:
    image: jguillermo/api-test:server-fake
    ports:
      - 8033:80
    networks:
      api-test-network:
        aliases:
          - next.json-generator.com
    volumes:
      - ./docker/server-fake/intercepted-route:/app/intercepted-route

  mysql:
    extends:
      file: docker-compose.yml
      service: mysql
    networks:
      - api-test-network

  test:
    image: jguillermo/api-test:latest
    volumes:
      - ./docker/node/e2e:/app/e2e
    networks:
      - api-test-network
    depends_on:
       - mysql
       - server
       - server-fake
    command: "/tmp/wait-for-it.sh mysql:3306 -t 50 -- npm test"

networks:
  api-test-network:
    driver: bridge